# Welcome to Jekyll!
#

# Site settings
title: Center for Molecular Biology of RNA
description: |
  Center for Molecular Biology of RNA at University of California, Santa Cruz
owner: Center for Molecular Biology of RNA # or company name
first_published: 2017 # if migrating another site, the year of your first publish
email: donohue@ucsc.edu
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://luckyluke007.github.io/rna-master/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
 sass_dir: _sass 
 style: compressed

exclude: ["README.md", "LICENSE.txt", "Gemfile", "Gemfile.lock", "Guardfile"]